### ISSUE TITLE
Fzf-lua integration

### ISSUE THREAD

**Issue by lucax88x** [aaronhallaert/advanced-git-search.nvim#12]
Would be possible to somehow reuse the code with fzf-lua?

Just wondering..

**Comment by aaronhallaert** [comment]
I do not have any experience with fzf-lua but I can certainly have a look at it.

**Comment by aaronhallaert** [comment]
@lucax88x Hi,
I ported all functions to fzf-lua, can you check out the linked PR and do some basic testing?
The readme explains how to setup for fzf-lua
