### ISSUE TITLE
Support neogit in addition to fugitive

### ISSUE THREAD

**Issue by schemar** [aaronhallaert/advanced-git-search.nvim#13]
Hey there,

Thank you for this super useful plugin, @aaronhallaert 💚 

I wanted to ask what you think about supporting [Neogit](https://github.com/TimUntersberger/neogit) in addition to vim-fugitive. There is a command (and a Lua API) to open a specific commit with it. It's not as good as a pure diff split for the current file, but I don't know if that's possible with Neogit.

Anyway:
1. What do you think about supporting Neogit as a fallback when fugitive cannot be found?
2. Would you like support for the addition?

**Comment by schemar** [comment]
Thanks! No worries. I wouldn't expect you to add it. Once the struggle gets big enough and I have enough time, I'll take a stab at it and open a PR.

**Comment by jemag** [comment]
Just throwing that out there, but it might make more sense to support [Diffview.nvim](https://github.com/sindrets/diffview.nvim/) since even Neogit integrates with Diffview for split diff

**Comment by aaronhallaert** [comment]
@jemag @schemar I opened a PR for this issue. Can you have a look at it? Anything I missed?
As @jemag noted, it made more sense to implement support for Diffview instead of Neogit.

**Comment by jemag** [comment]
@aaronhallaert hey just tried it, works great! Actually much prefer it to check diffs than Fugitive
