### ISSUE TITLE
How do you change telescope layout/theme?

### ISSUE THREAD

**Issue by genesistms** [aaronhallaert/advanced-git-search.nvim#14]

**Comment by aaronhallaert** [comment]
Changing the telescope theme/layout is part of [Telescope](https://github.com/nvim-telescope/telescope.nvim), this plugin does not apply themes.
https://github.com/nvim-telescope/telescope.nvim#themes

**Comment by genesistms** [comment]
Yes, that is true.

But i don't know if there is possibility to change options only for single call. 

For example when i want to change layout for your extension i need to edit global options, call your extension and then reload options back.

It would be nice to have possibility to add user options to your extension. I found this from [telescope wiki](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md)

> We will define a new function colors which accepts a table opts. This is good practice because now the user can change how telescope behaves by passing in their own opts table when calling colors.

> For example the user can pass in a configuration in opts which allows them to change the theme used for the picker. To allow this, we make sure to pass the opts table as the first argument to pickers.new. The second argument is a table which defines the default behavior of the picker.

**Comment by dlvhdr** [comment]
For example https://github.com/nvim-telescope/telescope-live-grep-args.nvim allows you to pass the layout config
