### ISSUE TITLE
Can we customize the previewer commands?

### ISSUE THREAD

**Issue by mmirus** [aaronhallaert/advanced-git-search.nvim#15]
Hi there! Is it possible to configure the previewer commands for the finders the extension provides?

For example, it would be nice to be able to modify the git command used at https://github.com/aaronhallaert/advanced-git-search.nvim/blob/main/lua/advanced_git_search/git_utils.lua#L173-L187 when I run `Telescope advanced_git_search diff_commit_file` so that I can pass flags that customize the diff output provided by git to work better in this context, compared to how I want to see it when I run git directly in the terminal.

**Comment by mmirus** [comment]
Exactly. For example, I have git configured to output diffs in a side-by-side view with [delta](https://github.com/dandavison/delta). This works great when I'm viewing diffs directly in the terminal, but not inside a Telescope window. You can pass config flags to git to change that when you run `git diff`, and if the git commands used by the plugin were configurable, then I could pass those flags (perhaps they already are and I'm just missing how!).

**Comment by aaronhallaert** [comment]
@mmirus Oke great, can you give the linked pull request a try?
