### ISSUE TITLE
Allow "entire git diff of the selected commit" with most searches

### ISSUE THREAD

**Issue by jemag** [aaronhallaert/advanced-git-search.nvim#25]
(Sorry for creating that many issues in a short amount of time, just enjoying using your plugin as part of my workflow)

Currently only `diff_commit_file` supports opening "entire git diff of the selected commit" with `<C-e>`. I think it would be great if other searches would support it as well, especially is https://github.com/aaronhallaert/advanced-git-search.nvim/issues/23 becomes possible.

For me, I often want to see that entire git diff more than the diff with the current file, so it would be quite useful to have it accessible across the board.

Thanks for the great plugin btw.

**Comment by aaronhallaert** [comment]
Good remark, I'll add it to all functions.
