### ISSUE TITLE
diff_commit_file: path exists on disk, but not in <commit hash> when viewing first commit for file

### ISSUE THREAD

**Issue by mmirus** [aaronhallaert/advanced-git-search.nvim#26]
Hey there!

I noticed that when you view the first commit in the list for `diff_commit_file`, you get this error: `fatal: path '<file path>' exists on disk, but not in '<commit hash>~'`.

![image](https://user-images.githubusercontent.com/524994/229588734-900496d8-b8e1-4ff5-8d40-3a7e030dd22c.png)

Is this a known issue / intended behavior? So far, it's occurred with every file I've tried.

Thank you!

**Comment by aaronhallaert** [comment]
It's a known problem, I'll create a workaround when I find the time. Now, the current file is diffed with the previous commit. The commit before the creation of the file does not contain the file (obviously). There is probably a better way to represent changes in a commit.

**Comment by mmirus** [comment]
Thanks! LMK if you want help testing when the time comes.

**Comment by aaronhallaert** [comment]
@mmirus I think the linked PR should do it. I didn't test extensively, only did some tests in my own projects with `diff_commit_file`. Will test later myself a bit more on the other functions (if applicable)

**Comment by mmirus** [comment]
Thank you!
