### ISSUE TITLE
Enhancement: add descriptions to keybindings

### ISSUE THREAD

**Issue by mmirus** [aaronhallaert/advanced-git-search.nvim#31]
Hi again! Would it be possible to add descriptions to the keybindings?

Here's an example of what I currently see when viewing the Telescope mappings for `diff_commit_file`.

![image](https://user-images.githubusercontent.com/524994/230420100-3b54d8b3-e193-4acb-8671-3a0ea230a313.png)

Showing something like the below would be more helpful:

- `<CR> -> Open file diff from commit`
- `<C-e> -> Open entire commit diff`
- `<C-o> -> Open commit in browser`

I'm not sure if there are any limitations on this on Telescope's end, though.

**Comment by aaronhallaert** [comment]
I'm doing a big refactor in https://github.com/aaronhallaert/advanced-git-search.nvim/pull/27 and actually implementing this 😅

**Comment by mmirus** [comment]
Thanks again!
