### ISSUE TITLE
Show git actions to include also builtin telescope git actions

### ISSUE THREAD

**Issue by drybalka** [aaronhallaert/advanced-git-search.nvim#39]
It would be convenient, in my opinion, to be able to have a single picker for all git actions. Do you think adding builtin telescope git pickers to “show_custom_functions” is a good idea?

**Comment by aaronhallaert** [comment]
Hi, great suggestion.
Can you try out the linked PR?
I made the functionality optional as I personally won't use this. (I'm using `lazygit` in a floatterm)

**Comment by drybalka** [comment]
Cool, it seems to be working. Thanks!
