### ISSUE TITLE
Invalid object name when using the function diff_branch_file

### ISSUE THREAD

**Issue by lunfel** [aaronhallaert/advanced-git-search.nvim#46]
I run the command `:Telescope advanced_git_search diff_branch_file` and get the following picker which says invalid object name.

![2023-06-15_00-57](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/1844873/6188f7bb-5c5a-4551-af80-47fea3b965a0)

If I select any branch, I always get the right side empty.

![2023-06-15_00-59](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/1844873/d36cd065-1b28-4096-b3cb-0c25be6d4557)

**Comment by lunfel** [comment]
Also, I tried using another function like `search_log_content` and it worked properly

**Comment by aaronhallaert** [comment]
@lunfel Thanks for reporting the issue, can you try the linked PR?

https://github.com/aaronhallaert/advanced-git-search.nvim/pull/47

**Comment by lunfel** [comment]
Wow thanks! That was really quick and responsive. Thanks for your efforts.

It seems like this fixed the issue. Here are some screenshots of it working.

![2023-06-17_15-56](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/1844873/49b8a4d7-091c-4c54-a9b0-ba06c29ced99)
![2023-06-17_15-57](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/1844873/4f6bdd60-ea62-4e66-9b90-8f8b776eba02)

Though, eere is the output when there are no change. I would suggest to add a small message to let the user know that there are no differences. At first glance, I thought it was broken, then I remembered that exit 0 means no error. I don't think this might be obvious to everyone so maybe adding a small message would be a nice touch.

![2023-06-17_15-56_1](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/1844873/964d9c0b-0016-47e8-a64f-1b3b01cf3215)

Thanks again

**Comment by aaronhallaert** [comment]
Thanks! Good idea to replace the "Process exited 0". I'll have a look at it later.
