### ISSUE TITLE
Add a gif?

### ISSUE THREAD

**Issue by joshpetit** [aaronhallaert/advanced-git-search.nvim#49]
Hey! I saw your plugin on a reddit post, and while I would like to try it but it would save me a lot of time if I could see a gif or video of the plugin at work with the features. If a picture is worth a 1000 words a short gif could help me with figuring everything out. Thanks :).

**Comment by aaronhallaert** [comment]
Hi! I totally agree, when I posted the plugin on reddit I made a video and linked it in the README of this repo. However, it would be a good idea to update it. I'll make a gif asap 😉

**Comment by joshpetit** [comment]
Fantastic! I just had another look and you did add a link to a video lolll reading comprehension is not my forte.
