### ISSUE TITLE
Scroll for specific file is not working

### ISSUE THREAD

**Issue by mbalazy** [aaronhallaert/advanced-git-search.nvim#54]
Hi,
When I'm using Telescope for finding other stuff I can always use `<C-d>` and `<C-u>` to scroll file window preview.
In your plugin this is not working. This could be a problem in my case or this is something that is not implemented?

Thank you for your time, extension is great!

**Comment by aaronhallaert** [comment]
This should work by default. Tested this with the following minimal config:

```lua
local M = {}

function M.root(root)
    local f = debug.getinfo(1, "S").source:sub(2)
    return vim.fn.fnamemodify(f, ":p:h:h") .. "/" .. (root or "")
end

---@param plugin string
function M.load(plugin)
    local name = plugin:match(".*/(.*)")
    local package_root = M.root(".tests/site/pack/deps/start/")
    if not vim.loop.fs_stat(package_root .. name) then
        print("Installing " .. plugin)
        vim.fn.mkdir(package_root, "p")
        vim.fn.system({
            "git",
            "clone",
            "--depth=1",
            "https://github.com/" .. plugin .. ".git",
            package_root .. "/" .. name,
        })
    end
end

function M.setup()
    vim.cmd([[set runtimepath=$VIMRUNTIME]])
    vim.opt.runtimepath:append(M.root())
    vim.opt.runtimepath:append("./")
    vim.opt.packpath = { M.root(".tests/site") }
    M.load("nvim-telescope/telescope.nvim")
    M.load("nvim-lua/plenary.nvim")
    vim.env.XDG_CONFIG_HOME = M.root(".tests/config")
    vim.env.XDG_DATA_HOME = M.root(".tests/data")
    vim.env.XDG_STATE_HOME = M.root(".tests/state")
    vim.env.XDG_CACHE_HOME = M.root(".tests/cache")

    print("Setup complete...\n")
end

M.setup()

require("telescope").setup({
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        },
        ["ui-select"] = { require("telescope.themes").get_dropdown() },
        advanced_git_search = {
            git_flags = { "-c", "delta.side-by-side=false" },
            git_diff_flags = {},
            show_builtin_git_pickers = true,
            diff_plugin = "diffview",
        },
    },
})

require("telescope").load_extension("advanced_git_search")
```

Open neovim in the plugins working directory with `nvim -u minimal_init.lua`

**Comment by arielschiavoni** [comment]
Hi @aaronhallaert, thanks for this great plugin!

I am also experiencing the same issue. `C-d` and `C-u` work as expected with the `builtin_git_pickers` but they don't work with the functions exposed by `advanced_git_search`. I thought the problem could be related to `delta` so I removed it from my git config but it did not help. 

I tried to run the minimal setup but unfortunately I get a bunch of other errors I am not familiarised with. I am not sure in which directory I should place this `minimal_init.lua` file.

**Comment by aaronhallaert** [comment]
@arielschiavoni I updated the minimal_init.lua so it doesn't matter where you run it. It downloads the `advanced-git-search` plugin with all dependencies (telescope and plenary). Could you try again with this config?

```lua
local M = {}

function M.root(root)
	local f = debug.getinfo(1, "S").source:sub(2)
	return vim.fn.fnamemodify(f, ":p:h:h") .. "/" .. (root or "")
end

---@param plugin string
function M.load(plugin)
	local name = plugin:match(".*/(.*)")
	local package_root = M.root(".tests/site/pack/deps/start/")
	if not vim.loop.fs_stat(package_root .. name) then
		print("Installing " .. plugin)
		vim.fn.mkdir(package_root, "p")
		vim.fn.system({
			"git",
			"clone",
			"--depth=1",
			"https://github.com/" .. plugin .. ".git",
			package_root .. "/" .. name,
		})
	end
end

function M.setup()
	vim.cmd([[set runtimepath=$VIMRUNTIME]])
	vim.opt.packpath = { M.root(".tests/site") }
	M.load("nvim-telescope/telescope.nvim")
	M.load("nvim-lua/plenary.nvim")
	M.load("aaronhallaert/advanced-git-search.nvim")
	vim.env.XDG_CONFIG_HOME = M.root(".tests/config")
	vim.env.XDG_DATA_HOME = M.root(".tests/data")
	vim.env.XDG_STATE_HOME = M.root(".tests/state")
	vim.env.XDG_CACHE_HOME = M.root(".tests/cache")

	print("Setup complete...\n")
end

M.setup()

require("telescope").setup({
	extensions = {
		advanced_git_search = {
			git_flags = { "-c", "delta.side-by-side=false" },
			git_diff_flags = {},
			show_builtin_git_pickers = true,
			diff_plugin = "diffview",
		},
	},
})

require("telescope").load_extension("advanced_git_search")
```

**Comment by arielschiavoni** [comment]
Hi @aaronhallaert ,

I could reproduce the bug with your `minimal_init.lua` file. I attached a screencast of it.

https://github.com/aaronhallaert/advanced-git-search.nvim/assets/1364564/18a1b06e-8489-4059-950d-a3394fc51361

**Comment by aaronhallaert** [comment]
Good that it is reproducible with the minimal config!
However, I still can't reproduce it (I set my version to neovim 0.9.2, to match yours), can I see your `.gitconfig`?

**Comment by arielschiavoni** [comment]
```
[init]
        defaultBranch = main
[core]
        excludesfile = ~/.gitignore_global
        editor = nvim
        pager = delta
        hooksPath = no-hooks
[color]
        ui = true
[push]
        default = simple
[credential]
        helper = cache --timeout=36000000
[pull]
        rebase = true
[fetch]
        prune = true
[commit]
        gpgSign = true
[interactive]
        diffFilter = delta --color-only
[delta]
        dark = true
        line-numbers = true
        side-by-side = false
        navigate = true
        keep-plus-minus-markers = false
        ; tokyonight_moon theme
        minus-style                   = syntax "#3a273a"
        minus-non-emph-style          = syntax "#3a273a"
        minus-emph-style              = syntax "#6b2e43"
        minus-empty-line-marker-style = syntax "#3a273a"
        line-numbers-minus-style      = "#b55a67"
        plus-style                    = syntax "#273849"
        plus-non-emph-style           = syntax "#273849"
        plus-emph-style               = syntax "#305f6f"
        plus-empty-line-marker-style  = syntax "#273849"
        line-numbers-plus-style       = "#627259"
        line-numbers-zero-style       = "#3b4261"
[merge]
        conflictstyle = diff3
[diff]
        colorMoved = default
[rebase]
        autoStash = true
[rerere]
        enabled = true
```

**Comment by aaronhallaert** [comment]
Can you try piping `delta` to `less`?
```
[core]
        pager = delta | less
```

However, you say it has nothing to do with delta? So you can also not scroll when `pager = delta` is removed.

I tested it with your `.gitconfig` and asked another user to test it (he uses neovim `0.9.1`), but sadly, we couldn't reproduce it.

Maybe it's related to the version of `delta` or `git`?

**Comment by arielschiavoni** [comment]
These are the versions I have installed.

- git: `2.42.0`
- delta: `0.16.5` 

The issue does not seem to be related to `delta` because I already tested it without `delta` and the problem still persists.

**Comment by aaronhallaert** [comment]
I could reproduce the issue with options passed to less through the `LESS` environment variable.

What does `echo $LESS` return in your case?

In my case it was just `R` (this will repaint the screen, but unrelated to this issue)
Whenever I added `X`, preview scrolling would not work.

```man
       -X or --no-init
              Disables sending the termcap initialization and 
              deinitialization strings to the terminal.  This is sometimes 
              desirable if the deinitialization string does something 
              unnecessary, like clearing the screen.
```

Related telescope issue: https://github.com/nvim-telescope/telescope.nvim/issues/253

**Comment by arielschiavoni** [comment]
Hi @aaronhallaert,

My `LESS` env variable was not defined (value was empty). I configured to with `-R` and now scrolling works with and without `delta`

Thank you!

**Comment by kapral18** [comment]
I tried everything here nothing works. In my case C-u and C-d is scrolling the main picker window instead of preview window.

I tried with telescope as well, the same result.

https://github.com/kapral18/config.nvim/blob/23d158436714444648144c8bcd53d0a0554d1c73/lua/plugins/git.lua#L18

nvim v 0.10.0

**Comment by aaronhallaert** [comment]
@kapral18 
I think your issue is not related to this plugin.
I tried your config (by using NVIM_APPNAME) and `<C-d>` and `<C-u>` also didn't work in other fzf-lua pickers:
* `<C-u>` wasn't doing anything. 
* `<C-d>` closed the picker entirely. 
* `<C-down>` and `<C-up>` did work, these are the defaults I think for scrolling the preview window in fzf-lua.

I modified your dotfiles a bit on the setup of `fzf-lua` to use the `telescope` profile where `<C-d>` and `<C-u>` are used to scroll the preview buffer.
```
  {
    "ibhagwan/fzf-lua",
    lazy = false,
    priority = 200,
    dependencies = { "nvim-tree/nvim-web-devicons" },
    config = function()
      require("fzf-lua").setup({ "telescope" })
    end,
  },
```
See https://github.com/ibhagwan/fzf-lua?tab=readme-ov-file#profiles for more information.

This got the `<C-d>` and `<C-u>` working for me.

**Comment by kapral18** [comment]
weird because c-d and c-u work in other fzf-lua pickers for previews for me. Anyways thanks for checking @aaronhallaert

**Comment by aaronhallaert** [comment]
@kapral18 
Oops, I tampered a bit too much with your config, it did work for other pickers.
However, I found the solution without making use of the `telescope` profile. You should add specific bindings in the `fzf` section of `keymap`

```lua
-- ...
        keymap = {
          builtin = {
            ["down"] = "down",
            ["up"] = "up",
            ["<F1>"] = "toggle-help",
            ["<F2>"] = "toggle-fullscreen",

            ["<F3>"] = "toggle-preview-wrap",
            ["<F4>"] = "toggle-preview",
            ["<F5>"] = "toggle-preview-ccw",
            ["<F6>"] = "toggle-preview-cw",

            ["<C-d>"] = "preview-page-down",
            ["<C-u>"] = "preview-page-up",
          },
          fzf = {
            ["down"] = "down",
            ["up"] = "up",
            ["ctrl-c"] = "abort",
            ["ctrl-a"] = "toggle-all",
            ["ctrl-q"] = "select-all+accept",
            ["f3"] = "toggle-preview-wrap",
            ["f4"] = "toggle-preview",
            ["ctrl-d"] = "preview-page-down",
            ["ctrl-u"] = "preview-page-up",
          },
        },
--...
```

**Comment by kapral18** [comment]
@aaronhallaert awesome thank you
