### ISSUE TITLE
Attempt to call a nil value with lazy.nvim

### ISSUE THREAD

**Issue by matawed** [aaronhallaert/advanced-git-search.nvim#55]
Running "Telescope advance_git_search" results in 

```
Error executing Lua callback: ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:193: attempt to call a nil value
stack traceback:
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'
	...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
	...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:107>
```

Nvim: 0.9.1
Telescope:  tag = '0.1.2'
advance-git-search.nvim: 79c9aab7aa1cf08c2a25d931719bcb408b381ed2
 
 reproduce with:
`:Telescope advanced_git_search`

config:

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
 
 require("lazy").setup({
    {
  "aaronhallaert/advanced-git-search.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      -- to show diff splits and open commits in browser
      "tpope/vim-fugitive",
      -- to open commits in browser with fugitive
      "tpope/vim-rhubarb",
      -- optional: to replace the diff from fugitive with diffview.nvim
      -- (fugitive is still needed to open in browser)
      -- "sindrets/diffview.nvim",
    },

    config = function()
      require("telescope").load_extension("advanced_git_search")
    end,
 
     }
 })    
 
```

**Comment by aaronhallaert** [comment]
Hi,
When using the `:Telescope advanced_git_search` command you should add the specific function as a second argument.
e.g. 
* `:Telescope advanced_git_search show_custom_functions`
*  `:Telescope advanced_git_search search_log_content`

For ease of use, I added a global command `:AdvancedGitSearch` with an optional function argument
* `:AdvancedGitSearch` => opens `show_custom_functions`
* `:AdvancedGitSearch {cmd}` => opens `cmd`

See README for further information

**Comment by matawed** [comment]
Ah, I see sorry. It seems it was already too late yesterday...

Maybe one last question before we close this issue. Isn't there a way to make a subcommand like `search_log_content`  available in Telescope when you run it without any parameters. I.e. run `:Telescope` or is it only possible for Telescope builtins?

**Comment by aaronhallaert** [comment]
@matawed 
I think you can do the following after setting up the extension.

```lua
require("telescope.builtin").search_log_content = require("advanced_git_search.telescope.pickers").search_log_content
```

When executing `:Telescope`, you'll get an entry `search_log_content`

**Comment by matawed** [comment]
That works, great, thanks a lot! Really appreciated!!!

Thank you for this project!
