### ISSUE TITLE
Toggle date and author binding overrides standard delete word binding

### ISSUE THREAD

**Issue by dudicoco** [aaronhallaert/advanced-git-search.nvim#58]
The binding for `<C-w>` which toggles date and author in entry overrides the standard binding for delete word in vim and in terminals in general. This means that whoever uses the standard binding to delete a word within the telescope prompt can't do this anymore.

It would be best to change this binding to something which does not interfere with standard bindings in insert mode.

**Comment by aaronhallaert** [comment]
@dudicoco I opened a PR for configurable keymaps, can you validate the behavior?

**Comment by dudicoco** [comment]
@aaronhallaert works, thanks!
