### ISSUE TITLE
"Bad revision" error when there is no diff to be shown

### ISSUE THREAD

**Issue by kkoomen** [aaronhallaert/advanced-git-search.nvim#59]
Hi, awesome plugin, exactly what I personally need.

Unfortunately when I run `diff_commit_file` or `search_log_content_file` when there is no diff to be shown, I get these errors:

### `:AdvancedGitSearch search_log_content_file`

```
fatal: ambiguous argument '39f498e~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

[Process exited 128]
```

<img width="1500" alt="image" src="https://github.com/aaronhallaert/advanced-git-search.nvim/assets/10693490/1c1ccfe0-7222-4ac8-ad82-af775e7ae536">

### `:AdvancedGitSearch diff_commit_file`

```
fatal: bad revision '39f498e~'

[Process exited 128]
```

# Reproduce

- Create a new folder, let's say `bufcommits
- Run `touch a.txt b.txt`
- `git add a.txt b.txt && commit -m 'added a.txt and b.txt'`
- `echo test > b.txt && commit -m 'added test into b.txt'`
- Open nvim via `nvim a.txt`
- Run any of the commands `:AdvancedGitSearch` with `diff_commit_file` or `search_log_content_file`

# Cause

As I mentioned before, the problem is solely because there is no contents thus no diff to be shown. Is this something you can handle to make it a little bit nicer rather than an error?

Here's what the contents look like when there is a diff:

<img width="1228" alt="image" src="https://github.com/aaronhallaert/advanced-git-search.nvim/assets/10693490/55a9f812-23ec-47c9-8d84-041e8d0856f2">

And here's what it looks like without changes:

<img width="1220" alt="image" src="https://github.com/aaronhallaert/advanced-git-search.nvim/assets/10693490/c033cfef-37d8-4278-8c8b-dfeeab88840f">

**Comment by aaronhallaert** [comment]
Hi, thanks for using the plugin and reporting the issue.
I had a quick look and I think I figured it out.
Can you try the branch `fix/bad_revision` (see the linked pull request)?

**Comment by kkoomen** [comment]
Works as expected!

Without contents:
<img width="1594" alt="image" src="https://github.com/aaronhallaert/advanced-git-search.nvim/assets/10693490/a75f1cf0-85f7-4936-b062-6fe24dbfec95">

With contents:
<img width="1594" alt="image" src="https://github.com/aaronhallaert/advanced-git-search.nvim/assets/10693490/98625a1a-e9e3-499a-be13-4f7c333a3e0d">
