### ISSUE TITLE
Preview scrolling is broken

### ISSUE THREAD

**Issue by dudicoco** [aaronhallaert/advanced-git-search.nvim#61]
I can not scroll the preview panel like I can with the default telescope builtin git commands.

I'm not sure how this plugin implements the preview diff but here is an example on how it differs from the native telescope diff:

telescope git_commits
![Screenshot 2024-02-16 at 13 05 58](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/51051860/751cc499-ee2d-420c-a9e8-f211fa1c5886)

advanced-git-search
![Screenshot 2024-02-16 at 13 09 12](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/51051860/266411d5-3b56-4a3d-a9e8-c07049f4dc32)

You can see the difference in colors and the `Process exited 0` message at the bottom of the advanced-git-search diff.

It cannot capture the scroll issue in a screenshot since the scroll doesn't work so I just included the screenshots above of a diff that does not require scrolling as it might help diagnose the issue.

**Comment by aaronhallaert** [comment]
The preview buffer is the output of a terminal command and uses a different buffertype than the ones of telescope's default git pickers.
Did you have a look at https://github.com/aaronhallaert/advanced-git-search.nvim/issues/54 ?
I think you should find an answer to your problem there (one of the last comments).

**Comment by dudicoco** [comment]
@aaronhallaert #54 is indeed the same issue, fixed by adding `export LESS=-R`.
Can you please clarify why this is needed?
