### ISSUE TITLE
Preview for search_log_content_file shows entire commit

### ISSUE THREAD

**Issue by dudicoco** [aaronhallaert/advanced-git-search.nvim#63]
The preview for `search_log_content_file`	currently shows the entire commit instead of only the current file diff within the commit. Same for `diff_commit_line`.

Is it possible to have the preview display only the relevant diff similar to telescope bcommits?

**Comment by dudicoco** [comment]
Hi @aaronhallaert, can we match the behavior of telescope `bcommits` / `bcommits_range`?

**Comment by aaronhallaert** [comment]
@dudicoco 
Can you check/verify the linked PR?
`diff_commit_line` should already follow the current file, can you give an example of where this goes wrong?

**Comment by dudicoco** [comment]
@aaronhallaert I can verify that the linked PR fixes `diff_commit_line`, thanks!

Regarding `diff_commit_line`, here is an example where I searched for the line `require("telescope").load_extension("live_grep_args")` with both `git_bcommits_range` and `diff_commit_line`.

The behavior of `git_bcommits_range` is to display the preview with the searched line highlighted:
![Screenshot 2024-04-06 at 14 06 27](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/51051860/9c841160-460e-420d-8ca9-abf2f47d1320)


`diff_commit_line` preview does not show the searched line, it shows the top of the commit:
![Screenshot 2024-04-06 at 14 07 38](https://github.com/aaronhallaert/advanced-git-search.nvim/assets/51051860/f3a175d0-0024-498a-be30-654b0bbaf959)

**Comment by aaronhallaert** [comment]
@dudicoco 
I made a new issue for matching the behavior of `git_bcommits_range`: https://github.com/aaronhallaert/advanced-git-search.nvim/issues/73
