### ISSUE TITLE
pass extra flags to `git log`

### ISSUE THREAD

**Issue by tronikelis** [aaronhallaert/advanced-git-search.nvim#82]
Hello,

I see there is flags for `git diff` command

```
    -- customize git in previewer
    -- e.g. flags such as { "--no-pager" }, or { "-c", "delta.side-by-side=false" }
    git_flags = {},
    -- customize git diff in previewer
    -- e.g. flags such as { "--raw" }
    git_diff_flags = {},
```

A quick read of the source code I don't find that `git_flags` are used in `git log` (correct me if i'm wrong)

I would want to pass `-C` to `git log` as it is useful

**Comment by aaronhallaert** [comment]
Hi @Tronikelis 

I'll have a look at this. I think the main problem will be that the `git` log` output is parsed based on the current format.
Changing the format will break the parsing which is needed for proper behavior.

**Comment by Tronikelis** [comment]
> Hi @Tronikelis 
> 
> I'll have a look at this. I think the main problem will be that the `git` log` output is parsed based on the current format.
> Changing the format will break the parsing which is needed for proper behavior.

Thanks! But -C does not change the format, only it makes git  more accurate, so i dont think that changing the format is necessary in this case

**Comment by aaronhallaert** [comment]
Ah valid point! There are indeed some useful flags to pass. Will try to add the option in the near future.

**Comment by aaronhallaert** [comment]
@tronikelis 
Can you try out the linked PR?
https://github.com/aaronhallaert/advanced-git-search.nvim/pull/84

**Comment by tronikelis** [comment]
> @tronikelis Can you try out the linked PR? #84

Hi, I created this issue while I was deciding which commit plugin to use, in the end I stuck with just the basic `telescope.builtin.git_bcommits` so I don't have this plugin installed :/

But I really appreciate the effort :muscle:
